export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';

export const SET_ERROR = 'SET_ERROR';
export const SET_LOADING = 'SET_LOADING';

export const SET_FORGOT_EMAIL = 'SET_FORGOT_EMAIL';
export const SET_FORGOT_OTP = 'SET_FORGOT_OTP';

export const SET_SNACKBAR_SUCCESS = 'SET_SNACKBAR_SUCCESS';
export const SET_SNACKBAR_ERROR = 'SET_SNACKBAR_ERROR';
export const SET_SNACKBAR_HIDE = 'SET_SNACKBAR_HIDE';

export const SET_IS_LOADING = 'SET_IS_LOADING';

export const SET_NEW_NOTIFICATION = 'SET_NEW_NOTIFICATION';

export const SET_SOCKET = 'SET_SOCKET';
